baseURL = "https://steadyspace.net/"
languageCode = "en-us"
title = "steady space"
theme = "PaperMod"

[params]
  env = "production"
  description = "a calming hub of digital tools and gentle guidance."
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
