baseURL = "https://steadyspace.net/"
languageCode = "en-us"
title = "steady space"
theme = "PaperMod"

[params]
  env = "production"
  description = "a calming hub of digital tools and gentle guidance."
  defaultTheme = "auto"
  mainSections = ["field-notes"]

[params.assets]
  customCSS = ["css/custom.css"]

[params.assets]
  favicon32x32 = "favicon-32x32.png"

[menu]
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "offerings"
    url = "/offerings/"
    weight = 1

  [[menu.main]]
    name = "say hello"
    url = "/say-hello/"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
